<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-13T10:29:17 IST" name="Suite" finished-at="2025-10-13T10:29:29 IST" duration-ms="11945">
    <groups>
      <group name="smoke">
        <method signature="ErrorValidationTest.incorrectEmailOrPassword()[pri:0, instance:SelFrameWork.ErrorValidationTest@1bb5a082]" name="incorrectEmailOrPassword" class="SelFrameWork.ErrorValidationTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2025-10-13T10:29:17 IST" name="ErrorValidationTest" finished-at="2025-10-13T10:29:29 IST" duration-ms="11945">
      <class name="SelFrameWork.ErrorValidationTest">
        <test-method is-config="true" signature="launchOpenPage()[pri:0, instance:SelFrameWork.ErrorValidationTest@1bb5a082]" started-at="2025-10-13T10:29:17 IST" name="launchOpenPage" finished-at="2025-10-13T10:29:21 IST" duration-ms="3772" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchOpenPage -->
        <test-method signature="LoginErrorTest()[pri:0, instance:SelFrameWork.ErrorValidationTest@1bb5a082]" started-at="2025-10-13T10:29:21 IST" name="LoginErrorTest" finished-at="2025-10-13T10:29:21 IST" duration-ms="586" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SelFrameWork.ErrorValidationTest@1bb5a082]" started-at="2025-10-13T10:29:21 IST" name="tearDown" finished-at="2025-10-13T10:29:22 IST" duration-ms="399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchOpenPage()[pri:0, instance:SelFrameWork.ErrorValidationTest@1bb5a082]" started-at="2025-10-13T10:29:22 IST" name="launchOpenPage" finished-at="2025-10-13T10:29:25 IST" duration-ms="3254" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchOpenPage -->
        <test-method retried="true" signature="incorrectEmailOrPassword()[pri:0, instance:SelFrameWork.ErrorValidationTest@1bb5a082]" started-at="2025-10-13T10:29:25 IST" name="incorrectEmailOrPassword" finished-at="2025-10-13T10:29:26 IST" duration-ms="701" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email o password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email o password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SelFrameWork.ErrorValidationTest.incorrectEmailOrPassword(ErrorValidationTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectEmailOrPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SelFrameWork.ErrorValidationTest@1bb5a082]" started-at="2025-10-13T10:29:26 IST" name="tearDown" finished-at="2025-10-13T10:29:26 IST" duration-ms="373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchOpenPage()[pri:0, instance:SelFrameWork.ErrorValidationTest@1bb5a082]" started-at="2025-10-13T10:29:26 IST" name="launchOpenPage" finished-at="2025-10-13T10:29:28 IST" duration-ms="1884" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchOpenPage -->
        <test-method signature="incorrectEmailOrPassword()[pri:0, instance:SelFrameWork.ErrorValidationTest@1bb5a082]" started-at="2025-10-13T10:29:28 IST" name="incorrectEmailOrPassword" finished-at="2025-10-13T10:29:29 IST" duration-ms="600" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email o password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email o password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SelFrameWork.ErrorValidationTest.incorrectEmailOrPassword(ErrorValidationTest.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incorrectEmailOrPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SelFrameWork.ErrorValidationTest@1bb5a082]" started-at="2025-10-13T10:29:29 IST" name="tearDown" finished-at="2025-10-13T10:29:29 IST" duration-ms="303" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SelFrameWork.ErrorValidationTest -->
    </test> <!-- ErrorValidationTest -->
  </suite> <!-- Suite -->
</testng-results>
